apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.43.0
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: configconnector-operator
  namespace: configconnector-operator-system
