# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/testing/workflows
    component: workflows
    name: unittests
    job_types: presubmit
