apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://5.6.7.8
  name: fake-cluster
contexts:
- context:
    cluster: fake-cluster
    namespace: default
    user: fake-user
  name: fake-context
current-context: ""
kind: Config
preferences: {}
users:
- name: fake-user
  user:
    password: "fake-password"
    username: "fake-username"