prowjob_namespace: prow
pod_namespace: test-pods
in_repo_config:
  enabled:
    "*": true
deck:
 spyglass:
   lenses:
   - lens:
       name: metadata
     required_files:
     - started.json|finished.json
   - lens:
       config:
       name: buildlog
     required_files:
     - build-log.txt
   - lens:
       name: junit
     required_files:
     - .*/junit.*\.xml
   - lens:
       name: podinfo
     required_files:
     - podinfo.json
plank:
  job_url_prefix_config:
    "*": http://prow.kubeflow-testing.com/view/
  job_url_template: 'http://prow.kubeflow-testing.com/view/s3/aws-kubeflow-jenkins/{{if eq .Spec.Type "presubmit"}}pr-logs/pull/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else}}logs{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}'
  report_templates:
    '*': >-
        [Full PR test history](http://prow.kubeflow-testing.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
        [Your PR dashboard](http://prow.kubeflow-testing.com/pr?query=is:pr+state:open+author:{{with
        index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
  default_decoration_configs:
    "*":
      gcs_configuration:
        bucket: s3://aws-kubeflow-jenkins
        path_strategy: explicit
      s3_credentials_secret: s3-credentials
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20210114-dfe4a7d4c0
        entrypoint: gcr.io/k8s-prow/entrypoint:v20210114-dfe4a7d4c0
        initupload: gcr.io/k8s-prow/initupload:v20210114-dfe4a7d4c0
        sidecar: gcr.io/k8s-prow/sidecar:v20210114-dfe4a7d4c0

presets:
# credential presets
- labels:
  preset-aws-cred: "true"
  env:
  - name: CLOUD_PROVIDER
    value: aws
  - name: AWS_DEFAULT_REGION
    value: us-west-2
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_EKS_CLUSTER
    value: optional-test-infra-argo
  - name: ARGO_ENDPOINT
    value: https://argo.kubeflow-testing.com/
  - name: ARTIFACTS_S3_BUCKET
    value: aws-kubeflow-jenkins

tide:
  merge_method:
    kserve/kserve: squash
  queries:
  - labels:
    - lgtm
    - approved
    missingLabels:
    - needs-rebase
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file
    orgs:
    - kserve
  target_url: # TODO: update tide link to https://$(prow-ingress)/tide

decorate_all_jobs: true

presubmits:
  kubeflow/katib:
  - name: kubeflow-katib-presubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    - release-0.11
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

  kubeflow/kfctl:
  - name: kubeflow-kfctl-presubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    - v1.2-branch
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

  kubeflow/kfserving:
  - name: kubeflow-kfserving-presubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

  kserve/kserve:
  - name: kubeflow-kserve-presubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

  kubeflow/kubeflow:
  - name: kubeflow-kubeflow-presubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    - v1.3-branch
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

  kubeflow/manifests:
  - name: kubeflow-manifests-presubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    - v1.2-branch
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

  kubeflow/pytorch-operator:
    - name: kubeflow-pytorch-operator-presubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
      branches:
      - master
      decorate: false
      labels:
        preset-aws-cred: "true"
      always_run: true
      spec:
        containers:
          - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
            imagePullPolicy: Always
            command: ["/usr/local/bin/run_workflows.sh"]

  kubeflow/testing:
  - name: kubeflow-testing-presubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

  kubeflow/tf-operator:
  - name: kubeflow-tf-operator-presubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    - all-in-one-operator
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

postsubmits:
  kubeflow/kubeflow:
  - name: kubeflow-kubeflow-postsubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    - v1.3-branch
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

  kubeflow/tf-operator:
  - name: kubeflow-tf-operator-postsubmit  # convention: (job type)-(repo name)-(suite name)-(test type)
    branches:
    - master
    - all-in-one-operator
    decorate: false
    labels:
      preset-aws-cred: "true"
    always_run: true
    spec:
      containers:
      - image: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/run_workflows.sh"]

periodics:
- interval: 1h
  agent: kubernetes
  name: infra-editor-sync
  labels:
    preset-aws-cred: "true"
  spec:
    containers:
    - image: public.ecr.aws/j1r0q0g6/daily-worker:latest
      command: ["/usr/local/bin/update-iam-assume-role-policy.sh"]
      env:
      - name: TRUST_POLICY
        value: https://raw.githubusercontent.com/kubeflow/testing/master/aws/Access/assume-role-access/infra-editor/trust-policy.json
      - name: ROLE_NAME
        value: infra-editor

- interval: 1h
  agent: kubernetes
  name: infra-viewer-sync
  labels:
    preset-aws-cred: "true"
  spec:
    containers:
    - image: public.ecr.aws/j1r0q0g6/daily-worker:latest
      command: ["/usr/local/bin/update-iam-assume-role-policy.sh"]
      env:
      - name: TRUST_POLICY
        value: https://raw.githubusercontent.com/kubeflow/testing/master/aws/Access/assume-role-access/infra-viewer/trust-policy.json
      - name: ROLE_NAME
        value: infra-viewer
