# A Tekton task to cleanup the kubeflow-ci-project
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cleanup-kubeflow-ci
  # TODO(jlewi): Should we use a ClusterTask
  namespace: tektoncd
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  inputs:
    params:
    - name: name
      type: string
      description: The name for the Kubeflow deployment
      default: "kf-vbp-{uid}"
    - name: project
      type: string
      description: The project to clean up.
      default: "kubeflow-ci-deployment"
    - name: management-cluster-name
      type: string
      description: The name of the management cluster.
      default: "kf-ci-management"
    - name: management-project
      type: string
      description: The project containing the management cluster
      default: kubeflow-ci
    - name: management-location
      type: string
      description: The location of the management cluster
      default: us-central1
    resources:
    - name: testing-repo
      type: git
      description: The GitHub repo containing kubeflow testing scripts
  steps:
  - name: create-context
    image: gcr.io/kubeflow-ci/test-worker-py3:d67009b@sha256:e96d069db00159c03b95ed1064569bcd0a78acdc691f42b5025050370949007a # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"test-image","value":"gcr.io/kubeflow-ci/test-worker-py3:d67009b@sha256:e96d069db00159c03b95ed1064569bcd0a78acdc691f42b5025050370949007a"}]}}
    command:
    - python
    - -m
    - kubeflow.testing.create_context
    - create
    - --name=$(inputs.params.management-project)
    - --project=$(inputs.params.management-project)
    - --location=$(inputs.params.management-location)
    - --cluster=$(inputs.params.management-cluster-name)
    - --namespace=$(inputs.params.project)
    env:
    - name: KUBECONFIG
      value: /workspace/kubeconfig
    - name: PYTHONPATH
      value: /workspace/$(inputs.resources.testing-repo.name)/py
  - name: cleanup-ci
    image: gcr.io/kubeflow-ci/test-worker-py3@sha256:b679ce5d7edbcc373fd7d28c57454f4f22ae987f200f601252b6dcca1fd8823b
    command:
    - python
    - -m
    - kubeflow.testing.cleanup_blueprints
    - auto-blueprints
    - --project=$(inputs.params.project)
    - --context=$(inputs.params.management-project)
    env:
    - name: KUBECONFIG
      value: /workspace/kubeconfig
    - name: PYTHONPATH
      value: /workspace/$(inputs.resources.testing-repo.name)/py
