# Use this script to launch oneoff runs of the cleanup job
# Mostly used to test code from a PR.
# The cron jobs are still defined in ksonnet and need to be ported over to YAML?kustomize
# The autodeploy jobs are a good model
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cleanup-kubeflow-ci-deployment-oneoff
  generateName: cleanup-kubeflow-ci-deployment-
  namespace: kubeflow-test-infra
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cleanup-kubeflow-ci-deployment-oneoff
    spec:
      containers:
      - command:
        - /bin/sh
        - -xc
        # TODO(jlewi): Switch to using init container to check things out
        - /usr/local/bin/checkout_repos.sh --repos=kubeflow/kubeflow@HEAD,kubeflow/testing@HEAD:570 --src_dir=/src; python -m kubeflow.testing.cleanup_ci --project=kubeflow-ci-deployment
          --gc_backend_services=true --dryrun service_account_bindings
        env:
        - name: PYTHONPATH
          value: /src/kubeflow/testing/py
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/key.json
        image: gcr.io/kubeflow-ci/test-worker@sha256:dd559f89b3cbd926ec563559995f25025eecc6290b3146f17f82d2f084d07ee2
        imagePullPolicy: IfNotPresent
        name: label-sync
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secret/gcp-credentials
          name: gcp-credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gcp-credentials
        secret:
          defaultMode: 420
          secretName: kubeflow-testing-credentials
